apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: testdoc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testdoc 
  name: testdoc
  namespace:  testdoc 
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: testdoc
    weight: 100 
